comp
====

. <<name,NAME>>
. <<synopsis,SYNOPSIS>>
. <<description,DESCRIPTION>>
. <<"see also","SEE ALSO">>
.\" Copyright (c) 2007 Jeff Epler
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\"
.\"


===== [[name]]NAME
comp -- Build, compile and install LinuxCNC HAL components


===== [[synopsis]]SYNOPSIS
.PD 0
.RS 5
.PP
**comp** [**--compile**|**--preprocess**|**--document**|**--view-doc**] compfile...
.RE
.PP
__sudo__ **comp** [**--install**|**--install-doc**] compfile...
.RS 5
.PP
**comp** **--compile** **--userspace** cfile...
.RE
.PP
__sudo__ **comp** **--install** **--userspace** cfile...
.PP
__sudo__ **comp** **--install** **--userspace** pyfile...
.PD


===== [[description]]DESCRIPTION
**comp** performs many different functions:
.IP \(bu 4
Compile **.comp** and **.c** files into **.so** or **.ko** HAL realtime components (the **--compile** flag)
.IP \(bu 4
Compile **.comp** and **.c** files into HAL userspace components (the **--compile --userspace** flag)
.IP \(bu 4
Preprocess **.comp** files into **.c** files (the **--preprocess** flag)
.IP \(bu 4
Extract documentation from **.comp** files into **.9** manpage files (the **--document** flag)
.IP \(bu 4
Display documentation from **.comp** files onscreen (the **--view-doc** flag)
.IP \(bu 4
Compile and install **.comp** and **.c** files into the proper directory for HAL realtime components (the **--install** flag), which may require __sudo__ to write to system directories.
.IP \(bu 4
Install **.c** and **.py** files into the proper directory for HAL userspace components (the **--install --userspace** flag), which may require __sudo__ to write to system directories.
.IP \(bu 4
Extract documentation from **.comp** files into **.9** manpage files in the proper system directory (the **--install** flag), which may require __sudo__ to write to system directories.
.IP \(bu 4
Preprocess **.comp** files into **.c** files (the **--preprocess** flag)


===== [["see also"]]"SEE ALSO"
__Comp HAL Component Generator__ in the LinuxCNC documentation for a full description of the **.comp** syntax, along with examples

**pydoc hal** and __Creating Userspace Python Components__ in the LinuxCNC documentation for documentation on the Python interface to HAL components

**comp(9)** for documentation on the "two input comparator with hysteresis", a HAL realtime component with the same name as this program
